on: push
name: solvers test
jobs:
        UT:
                name: unit tests
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@master
                        - run: pip install pytest
                        - run: pytest -v
