on: push
name: solvers test
jobs:
        UT:
                name: unit tests
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@master
                        - name: solvers unit tests
                          uses: cclaus/Github-Action-for-pytest@master
                          with:
                              args:pytest -v
