on: push
name: solvers test
jobs:
        UT:
                name: unit tests
                runs-on: ubuntu-latest
                strategy:
                  matrix:
                    python-version:[3.6]
                steps:
                        - uses: actions/checkout@master
                        - run: pip install pytest stopit gym-mapf
                        - run: pytest -v
