on: push
name: solvers test
jobs:
        UT:
                name: unit tests
                runs-on: ubuntu-latest
                matrix:
                  python-version:[3.6]
                steps:
                        - uses: actions/checkout@master
                        - run: pip install pytest
                        - run: pip install stopit
                        - run: pytest -v
