on: push
name: solvers test
jobs:
        UT:
                name: unit tests
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@master
                        - uses: actions/setup-python@v2
                          with:
                            python-version: '3.6'
                        - run: pip install pytest stopit gym-mapf numpy
                        - run: pytest -v
                          env:
                            PYTHONPATH: "."
