on: push
name: solvers test
jobs:
        UT:
                name: solver unit tests
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@master
                        - name: solvers unit tests
                          uses: actions/research@master
                          env:
                                  PYTHONPATH: `pwd`
                          run:
                                  pytest -v
